### PR TITLE
Toggle favorite text, fix bug #375

### LINKED ISSUE #375: [Bug] Toggle favorites in context menu
**To Reproduce**
- Create two notes. 
- Add one to favorites.
- Select both notes.
- Open context menu.

**Expected behavior**
The text should say "Toggle favorite"

**Actual behavior**
Sometimes it says "Add to favorites", sometimes it says "Remove from favorites". It should say toggle when both options will happen.

**Notes**
If someone can think of better behavior for this (always "add to favorites" in context menu when multiple are selected of different types?) I'm open to it.

### PR DESCRIPTION
**Pull request by qpeela**
## Description

Change text in context menu to "Toggle favorite" when selected notes has different favorite state. 

Closes #375

### Browser checklist

This PR has been tested in the following browsers:

- [x] Chrome
- [x] Firefox
- [x] Safari

### CODE REVIEW

File: src/client/containers/ContextMenuOptions.tsx [hunk 1]
```diff
@@ -100,6 +100,10 @@ const NotesOptions: React.FC<NotesOptionsProps> = ({ clickedNote }) => {
   const { selectedNotesIds, notes } = useSelector(getNotes)
   const { categories } = useSelector(getCategories)
 
+  const selectedNotes = notes.filter((note) => selectedNotesIds.includes(note.id))
+  const isSelectedNotesDiffFavor =
```
Comment (taniarascia) [inline src/client/containers/ContextMenuOptions.tsx:104]: Couldn't this just be a `find`?

Comment (qpeela) [reply src/client/containers/ContextMenuOptions.tsx:104]: You mean `isSelectedNotesDiffFavor`?

**Comment by taniarascia** [comment]
@all-contributors add @qpeela for code, bug
